Multicall CCIP-read gateway
ensdomains/offchain-resolver pull request #22
Opened 2022-08-01 21:41 UTC by makoto

Resolve https://github.com/ensdomains/offchain-resolver/issues/17

2022-08-17 22:28 UTC, Arachnid requested changes

2022-08-17 22:28 UTC, Arachnid commented on packages/batchclient/src/index.ts
> +import { formatsByCoinType } from '@ensdomains/address-encoder';
Can't all of this be replaced by a simple call to Ethers to resolve the name now?

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/README.md
> +`private-key` should be an Ethereum private key that will be used to sign messages. You should configure your resolver contract to expect messages to be signed using the corresponding address.
Why is the batch gateway signing messages?

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/src/index.ts
> +const program = new Command();
```suggestion
import { Command } from 'commander';

const program = new Command();
```

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/src/json.ts
> +import { Database } from './server';
This file should be unnecessary for the batch gateway.

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/src/offchainexample.eth.json
> +{
This file should be unnecessary for the batch gateway.

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/src/server.ts
> +              .replace('{data}', callData);
If `{data}` isn't present, this should send a POST request, per EIP 3668.

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/test.eth.json
> +{
This shouldn't be necessary for the batch gateway.

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/src/utils.ts
> +export const ETH_COIN_TYPE = 60;
This shouldn't be necessary for the batch gateway.

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/test/e2e.test.ts
> +const TEST_DB = {
None of this should be needed.

2022-08-17 22:28 UTC, Arachnid commented on packages/batchgateway/test/e2e.test.ts
> +describe('End to end test', () => {
This looks like it's testing the resolver gateway?

2022-08-29 19:39 UTC, makoto commented
Deprecated. The new PR is https://github.com/ensdomains/batch-gateway/pull/1

2022-08-29 19:39 UTC, closed without merging